# Generated by Django 5.0.6 on 2024-06-25 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('applicationID', models.AutoField(primary_key=True, serialize=False)),
                ('durationOfLoan', models.IntegerField()),
                ('purpose', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Submitted', max_length=20)),
                ('applicationDate', models.DateField(auto_now_add=True)),
                ('approvalDate', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
