# Generated by Django 5.0.6 on 2024-06-25 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loanID', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('durationOfLoan', models.IntegerField()),
                ('purpose', models.CharField(max_length=255)),
                ('interest_rate', models.FloatField()),
                ('approvalDate', models.DateField(auto_now_add=True)),
                ('repayment_schedule', models.JSONField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan_management.loanapplication')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
