# Generated by Django 5.0.6 on 2024-06-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0002_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Fully Paid', 'Fully Paid'), ('Overdue', 'Overdue'), ('Defaulted', 'Defaulted')], default='Ongoing', max_length=20),
        ),
    ]
