# Generated by Django 5.0.6 on 2024-06-26 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0003_loan_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('documentID', models.AutoField(primary_key=True, serialize=False)),
                ('documentType', models.CharField(choices=[('ID Proof', 'ID Proof'), ('Income Proof', 'Income Proof')], max_length=50)),
                ('documentPath', models.FileField(upload_to='documents/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_management.loanapplication')),
            ],
        ),
    ]
