# Generated by Django 5.0.6 on 2024-06-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0004_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
